### ISSUE TITLE
hi tobias

### ISSUE THREAD

**Issue by ashraf-01** [tobiasbrodd/backtester#1]
thanks for the effort , after having a closer look in to the overall framework , I can't see where does it adapt to different types of orders , I see you have used type : market in all over the examples that you provided within the module , is it possible to define OTHER TYPES LIKE LIMITS AND MARKET PEGGED type of orders ?
secondly , would you provide an example where you trade two legs  / two instruments say on the same trade , say short SPY while long calls at the same time by an amount calculated according to other trading rules like delta , gamma ...etc ?

looking forward to your response 
ashraf

**Comment by tobiasbrodd** [comment]
Hi ashram-01, sorry for the late response. The current version of the backtester only supports "standard" orders. This can however be changed by adding more order event types and then adding logic to support those order types in the SimulateExecutionHandler class. 

Regarding multiple orders, you should be able to just add two separate order events from your strategy class to for example buy stock A and sell stock B at the same time. Here's an example:
```
long_signal = SignalEvent(symbol_a, date, 'LONG', quantity)
short_signal = SignalEvent(symbol_b, date, 'SHORT', quantity)
self.events.put(long_signal)
self.events.put(short_signal)
```
